### ISSUE TITLE
Tuple item0 vs item1

### ISSUE THREAD

**Issue by iulian0512** [andrewackerman/darq#11]
I understand that most of this library is inspired from C# Linq extension methods, but what i can't understand is why didn't you implement the tuples like in C# Tuple2 has item1 and item2 ?

**Comment by tofutim** [comment]
I also vote for item1/item2 to match with the tuple library. That will make it much easier to switch between your library and that one. As is, I would have to modify a bunch of code, or just have both tuple.dart and darq.dart. I have some cases where I am using `Tuple4` and more, and I would have to rewrite a lot of code.

tl;dr; should match C# and tuple.dart library otherwise it is hard to port from C# (which I'm doing) and switch from using tuple.dart (which I'm doing)
---

**Update. ** But I suppose index is 0 so that we can tuple[2] for the third tuple item. Was that the reasoning? I decided to go for 0 indexing. Don't change it! Lol.

**Comment by Abion47** [comment]
The intention was that `TupleX.item0` will match the value that is in `TupleX[0]`. Though it's true that this diverges from expected behavior when porting code from C#, which sort of goes against the idea that this package is a faithful re-adaptation of LINQ in Dart. 

On the other hand, this package has been out for a while with people using it, and suddenly shifting it so that `item0` becomes `item1`, `item1` becomes `item2`, and so on, is a pretty significant change that is breaking at best and subtle at worst. (If someone is using tuples in their project but only explicitly references `item1` or higher, this change will change the behavior without alerting the developer of the change, producing catastrophic silent errors.)

For now, I'm going to consider maintaining current behavior more important than perfect parity. If the package ever sees a major version change, and if enough people are echoing this issue, I will consider making this change then.
